### ISSUE TITLE
presentChatNameDialog

### ISSUE THREAD

**Issue by FredvanRijswijk** [dmendels/chatDemo#1]
Little bug after downloading this git, if you want to run it it gives the following error:

presentChatNameDialog

receiver type 'DMChatRoomViewController' for instance message does not declare a method with selector 'presentChatNameDialog'

**Comment by dmendels** [comment]
Just updated the project, added -(void)presentChatNameDialog to the .h in order to silence this one. Am afraid it never showed in my tests, we may not be using the same compiler (LLVM?).
Hope it fixes it.

**Comment by FredvanRijswijk** [comment]
Quick response... ;-)

LLVM 3.0 standard, also added the -(void)presentChatNameDialog

nice blog post and clean code ! thnx

**Comment by dmendels** [comment]
Was in front of the computer and not on call when it popped up :-P
Same here, LLVM3, I guess I'll put that on the #Idontknowwhatthehellhappened list, I didn't get even a warning, and shouldn't as it is defined below. Bah!
Happy that you like it anyway, hope it will be useful.

Cheers,

David.
